language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 6.0.202
branches:
  only:
    - master
#    - develop
script:
  - dotnet build
  - dotnet test
# [START travis_deploy]
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: travisci-marzo23-7dae9681e272.json
    project: travisci-marzo23
    version: service-demo
    default: true
    on:
        all_branches: true
# [END travis_deploy]